#------------------------------------------------
# This is the Helm Source for the application external secrets
# Flux will use this to install the helm chart for external secrets
#------------------------------------------------
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rancher
  namespace: ${FLUX_SOURCE_NS:=flux-sources}
spec:
  interval: 1m0s
  url: https://releases.rancher.com/server-charts/stable  # <- This is the URL to the helm Repository
  timeout: 60s
