#------------------------------------------------
# The Git source flux will use for external-secrets
# (Itself)
#------------------------------------------------
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-secrets-git
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  timeout: 60s
  url: ssh://git@github.com/devbot-cloud/workloads.git
  ignore: |
    # Exclude Everything
    /*
    # include external-secrets
    !/external-secrets/
---
#------------------------------------------------
# Flux will use this kustomize to deploy the helm release external-secrets 
#------------------------------------------------
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets
  namespace: ${CLUSTER_NAME:=flux-system}
spec:
  interval: 1m0s
  path: ./external-secrets/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-secrets-git
    namespace: flux-system
  validation: server
  timeout: 2m
  healthChecks: # <--- Perform health checks on the helm release
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: external-secrets
      namespace: ${CLUSTER_NAME:=flux-system}
  postBuild:
    substituteFrom:
      # - kind: ConfigMap
      #   name: workload-versions  # Use this ConfigMap if it exists, but proceed if it doesn't.
      #   optional: true
      - kind: ConfigMap
        name: cluster-env
---
#------------------------------------------------
# Flux will use this kustomize to deploy the yaml for external-secrets 
#------------------------------------------------
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-yaml
  namespace: ${CLUSTER_NAME:=flux-system}
spec:
# -------------
# The Kubeconfig Used to by kustomize to applied the manifest generated
  kubeConfig:
    secretRef:
      name: ${CLUSTER_NAME}-kubeconfig  # <--- The remote kubeconfig to use to apply the manifest
# -------------
  dependsOn:
    - name: external-secrets
      namespace: ${CLUSTER_NAME:=flux-system}
  interval: 1m0s
  path: ./external-secrets/yaml
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: external-secrets-git
    namespace: flux-system
  validation: server
  timeout: 60s
  postBuild:
    substituteFrom:
      # - kind: ConfigMap
      #   name: workload-versions  # Use this ConfigMap if it exists, but proceed if it doesn't.
      #   optional: true
      - kind: ConfigMap
        name: cluster-env