#------------------------------------------------
# This is the Helm Release for the application external secrets
# Flux will install external secrets onto the remote cluster
# using the kubeconfig stored in the secret (CLUSTERNAME)-kubeconfig
# This can be controlled by installing the release into the clusters namespace
#------------------------------------------------
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: ${CLUSTER_NAME:=flux-system}
spec:
# -------------
# The Kubeconfig Used to by HelmRelease to install the helm chart
  kubeConfig:
    secretRef:
      name: ${CLUSTER_NAME}-kubeconfig  # <--- The remote kubeconfig to use to apply the manifest
# -------------
  releaseName: external-secrets           # <- This will be the name of the helm release on the remote cluster
  targetNamespace: external-secrets      # <- This will be the namespace the helm release will be installed into on the remote cluster
  interval: 1m0s
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: ${EXTERNAL_SECRETS_VERSION:=8.5.5}
  timeout: 1m0s
  upgrade:
    remediation:
      retries: 1
      retryInterval: 1m0s
    strategy:
      type: Recreate
  wait: true
# -------------
# This allows us to use the values.yaml file in the helm chart 
# This configmap can be created in each clusters namespace 
# and will be used to configure the helm release per cluster
# -------------
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-values
      valuesKey: values.yaml
      optional: true