#------------------------------------------------
# This is the Helm Source for the application external secrets
# Flux will use this to install the helm chart for external secrets
#------------------------------------------------
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://external-secrets.github.io/kubernetes-external-secrets/    # <- This is the URL to the helm Repository
  timeout: 10s
